name: new 
on : [workflow_dispatch]

#
jobs:
    print:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: print something
              run:  echo hello world #run
